### PR TITLE
Fix dictionary JSON struct default values

### LINKED ISSUE #925: Incorrect default value JSON dictionary entry for member arrays of arrays
I believe I have found an issue with the JSON dictionary generated by this FPP:
```
        struct ExampleStruct {
            arrayMemberU32: [2] U32Array,
        }
```

Where U32Array is:
```
array U32Array = [5] U32
```

That generates this JSON:
```
    {
      "kind" : "struct",
      "qualifiedName" : "ExampleStruct",
      "members" : {
        "ex" : {
          "type" : {
            "name" : "U32Array",
            "kind" : "qualifiedIdentifier"
          },
          "index" : 0,
          "size" : 2
        }
      },
      "default" : {
        "ex" : [
          0,
          0,
          0,
          0,
          0
        ]
      }
    },
```

Notice that the default value does not match the actual structure of the member. Instead, I expect something like:

```
      "default" : {
        "ex" : [[
          0,
          0,
          0,
          0,
          0
        ], [
          0,
          0,
          0,
          0,
          0
        ]]
      }
```

### PR DESCRIPTION
**Pull request by jwest115**
- Takes into account struct member sizes when generating struct value dictionary JSON
- Clean up some redundant code for array JSON
- Updated dictionary tests to exercise struct member size case

Closes #925

### CODE REVIEW

**Comment by bocchino** [comment]
This looks good, but now that I see the change, I don't think we want to expand the default values for struct array members. I added a comment to #925. I think we should just write out the default value of the struct, as the value is represented in FPP. If there's some reason that won't work in the GDS, we should try to address it on the GDS side.

File: compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala [hunk 1]
```diff
@@ -197,7 +202,7 @@ case class DictionaryJsonEncoder(
                 val qualifiedName = dictionaryState.a.getQualifiedName(Symbol.Enum(t.node)).toString
                 s"${qualifiedName}.${v._1}".asJson // FQN of the enum constant
             }
-            case Value.Struct(Value.AnonStruct(members), t) => members.map((key, value) => (key.toString -> valueAsJson(value))).asJson
```
Comment (bocchino) [inline compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala:200]: As noted, the original code looks more correct here. The new code seems to be a special case to implement a difference between FPP semantics and GDS semantics. I'd rather keep those the same, if possible.

File: compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala [hunk 2]
```diff
@@ -169,17 +169,22 @@ case class DictionaryJsonEncoder(
...
-        val arrayRes = for(e <- elements) yield {
-            val res = e match {
-                // Case where array is N-dimensional
-                case Value.Array(a, t) => arrayElementsAsJson(a.elements)
-                case _ => valueAsJson(e)
-            }
-
-            res.asJson
-        }
+        val arrayRes = for(e <- elements) yield valueAsJson(e)
```
Comment (bocchino) [inline compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala:172]: This looks like a code improvement (eliminating a special case). Can we keep this change and preserve the existing behavior?

File: compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala [hunk 3]
```diff
@@ -169,17 +169,22 @@ case class DictionaryJsonEncoder(
...
         arrayRes.asJson
     }
+
```
Comment (bocchino) [inline compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala:175]: As discussed in issue #925, after further discussion, I think we should revert this change. The current behavior is correct according to the way that FPP represents struct values with member arrays. However, @jwest115 can you make sure that the current F Prime JSON spec is consistent with the FPP model and the generated JSON here? This is a tricky case.

Comment (bocchino) [reply compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala:175]: Now I'm not so sure if we should revert. I think the root cause of the issue is that the dictionary JSON is underspecified here. I opened an issue on this: https://github.com/nasa/fprime/issues/4787. There are at least two ways this could work:

1. When a struct member of type _T_ has a size _n_, the value stored in the member must be a JSON array with _n_ elements, each of type _T_. When there is no size, the value must be a single value of type _T_.

2. Regardless of whether the struct member has a size, the value stored in the member can be a single value or an array. If there is no size and an array of elements, the array size must be one. If there is a size and a single element, the single element is stored in every position in the array.

Probably we want option (1), but the JSON spec does not specify what behavior is intended. We should tighten up the JSON spec first, and then make the `fpp-to-json` output conform to it.

File: compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala (hunk 1 above)
Comment (bocchino) [reply compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala:200]: After discussion, we decided to keep the code gen change here.

File: compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala (hunk 3 above)
Comment (bocchino) [reply compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala:175]: We decided to go with option (1).

File: compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala [hunk 4]
```diff
@@ -280,7 +285,7 @@ case class DictionaryJsonEncoder(
                         "members" -> membersFormatted.toMap.asJson,
                     )
                     val optionalValues = Map(
-                        "default" -> default, 
+                        "default" ->  default.map(structValueAsJson),
```
Comment (bocchino) [inline compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala]: Why is this special case (struct value as default of struct type) called out here? It seems to me the general-case code for writing a struct value should work here and in all other cases, e.g., a struct as a member of a struct or array.

Comment (bocchino) [reply compiler/lib/src/main/scala/codegen/DictionaryJsonWriter/DictionaryJsonEncoder.scala]: I removed the special-case code.

**Review by bocchino — APPROVED** [review]
Looks good!
